### ISSUE TITLE
Error: unhandled exception: Call to 'sendQuery' timed out. [TimeoutError]

### ISSUE THREAD

**Issue by tr1fled** [ba0f3/dnsclient.nim#14]
i'm trying to use the library, but no matter which record i try to query, i always get the following error
```
Error: unhandled exception: Call to 'sendQuery' timed out. [TimeoutError]
```
even when running `dnsclient` on the command line, i get the following:
```
dnsclient.nim(49)        sendQuery
Error: unhandled exception: Call to 'sendQuery' timed out. [TimeoutError]
```
how can i fix this?

**Comment by ba0f3** [comment]
What's the dns server you are using to do query? Can you gimme a your code snippet?

**Comment by tr1fled** [comment]
the snippet is:
```
import dnsclient

let client = newDNSClient()
let resp = client.sendQuery("google.com", A)
assert resp.answers[0].kind == TXT
let rr = TXTRecord(resp.answers[0])
echo rr.toString()
```
it seems to use 8.8.8.8, and according to wireshark, there is a query but not a response
![image](https://github.com/user-attachments/assets/2604321b-b440-4a89-9559-ffb634dbf73a)

PS: below is an image of the captured DNS payloads, the white space below is the rest of the list, in this case, nothing, because we receive no response. and for reference, i am using kubuntu (basically ubuntu but with KDE).

**Comment by ba0f3** [comment]
does  this command `dig @8.8.8.8 TXT google.com` return anything?

**Comment by tr1fled** [comment]
i got the following:
```
$ dig @8.8.8.8 TXT google.com
;; communications error to 8.8.8.8#53: timed out
```
same with 1.1.1.1

**Comment by ba0f3** [comment]
I think your network blocked DNS traffic to Google and Cloudflare. Try to specify DNS server you are using!

**Comment by tr1fled** [comment]
this issue has been solved. i was using my local dns server and i suppose kubuntu doesnt like other dns servers? anyways, thanks for the help. 👍
